// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unquhlkedcxkcmdhxclr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucXVobGtlZGN4a2NtZGh4Y2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTg3MDQsImV4cCI6MjA2MjQzNDcwNH0.np3kFsWVuVVHWhO9leRLQtmDBLZoH4v1BZSsMAaXiyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);